### ISSUE TITLE
BMI APP CALCULATING THE BMI of USERS

### ISSUE THREAD

**Issue by prerna12s** [SnowScriptWinterOfCode/Flutter-Projects#4]
Implementations of these features:
1. add a splash screen 
2. both light and dark themes
3. Calculation of BMI of users with their height and weight in different measurement systems
4. Show them about their current BMI report

**Comment by prerna12s** [comment]
@Nitya-Pasrija @Namya13Jain Kindly assign this issue   to me !

**Comment by Namya13Jain** [comment]
@prerna12s assigned the issue to you!! Happy contribution 🙌
